on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:18
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm install -g nodemon
      - run: ping google.com
      - run: ping 172.18.0.2
      - run: nodemon app.js